Retire VS 2016, gcc7 and gcc8
open-simulation-platform/libcosim pull request #683
Opened 2022-02-16 17:59 UTC by markaren

This PR removes old compilers from the CI. It does not add new ones.
VS2016 must be removed soon anyway (deprecated in the runners). 
gcc7 and gcc8 does not support `<execution>` in C++17, which we aim to use in the future.

2022-02-17 08:55 UTC, THEvang approved these changes

2022-02-17 08:57 UTC, markaren commented
I will need further confirmation that `gcc8` can be removed. We only discussed `gcc7` in the meeting.

2022-02-17 09:41 UTC, eidekrist commented
I'm OK with this, but can't comment on the need (or lack thereof) for building with GCC 8. 

If I remember correctly the rationale for supporting GCC 7 was that it shipped with Ubuntu 18.04?

2022-02-17 09:41 UTC, eidekrist approved these changes

2022-02-17 09:47 UTC, markaren commented
Ubuntu 18.04 ships with gcc 7.5. Ubuntu 20.04 ships with gcc 9.3.

2022-02-17 10:13 UTC, davidhjp01 approved these changes
LGTM!

2022-02-18 12:32 UTC, ljamt requested changes
As `<execution>` will not be an issue for the threadpool solution, I suggest holding off removing gcc7 and gcc8 for a while. Lets remove VS2016 though.

2022-02-18 13:04 UTC, closed without merging